# Emergency Procedures
emergency_actions:
  low_battery: 
    action: return_to_home
    threshold: 20.0  # %
  signal_loss:
    action: hover_land
    timeout: 30.0     # seconds
  system_error:
    action: immediate_land
    error_levels: [CRITICAL, FATAL]

geofence_violation:
  response: force_land
  buffer_zone: 10.0  # meters

environmental_limits:
  max_wind_speed: 12.0  # m/s
  min_temperature: -10.0 # °C 
  max_temperature: 40.0  # °C

system_checks:
  gps_satellites: 
    required: 6
    redundancy: 2
  imu_redundancy: 3
  preflight_checks: [battery, gps, compass, payload]

data_validation:
  command_ranges:
    altitude: [2.0, 120.0]
    speed: [0.5, 18.0]
    heading: [0.0, 360.0]
  sanity_checks: 
    enabled: true
    max_acceleration: 5.0 # m/s²

recovery_settings:
  max_auto_recovery_attempts: 3
  safe_landing_altitude: 5.0  # meters
  emergency_descent_rate: 2.0 # m/s
